buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'org.ysb33r.gradle:bintray:1.0'
        classpath 'org.jfrog.buildinfo:build-info-extractor-gradle:2.2.3'
        classpath "io.codearte.gradle.nexus:gradle-nexus-staging-plugin:0.5.3"
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'artifactory'
apply plugin: 'maven'
apply plugin: 'signing'
apply plugin: 'bintray-publish'
apply plugin: 'maven-publish'
apply plugin: 'io.codearte.nexus-staging'

version = '0.4.5'
group = 'net.sourceforge.jdistlib'
archivesBaseName = 'jdistlib'

// Javadoc in this codeset fails doclint on JDK8, so let's turn it off
// As per http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html
if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
        tasks.withType(Javadoc) {
            options.addStringOption('Xdoclint:none', '-quiet')
        }
    }
}

repositories {
    jcenter()
}

dependencies {
    testCompile 'junit:junit:4.10'
}

jar {
    manifest {
        attributes 'Implementation-Title': 'JDistLib', 'Implementation-Version': version
    }
}

task sourcesJar(type: Jar, dependsOn: classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

task javadocJar(type: Jar) {
    description "An archive of the JavaDocs for Maven Central"
    classifier "javadoc"
    from javadoc
}

artifacts {
    archives sourcesJar, javadocJar
}

signing {
    sign configurations.archives
}

uploadArchives {
    repositories {
        mavenDeployer {
            if(!version.endsWith("SNAPSHOT")) {
                beforeDeployment { MavenDeployment deployment -> signing.signPom(deployment) }

                repository(url: "https://oss.sonatype.org/service/local/staging/deploy/maven2/") {
                    authentication(userName: ossrhUsername, password: ossrhPassword)
                }

                snapshotRepository(url: "https://oss.sonatype.org/content/repositories/snapshots/") {
                    authentication(userName: ossrhUsername, password: ossrhPassword)
                }

                pom.project {
                    name 'JDistlib'
                    packaging 'jar'
                    artifactId 'jdistlib'
                    description 'A Java package that provides routines for various statistical distributions.'
                    url 'http://jdistlib.sourceforge.net'

                    scm {
                        connection 'scm:git:git://git.code.sf.net/p/jdistlib/code/'
                        developerConnection 'scm:git:git://git.code.sf.net/p/jdistlib/code/'
                        url 'https://sourceforge.net/p/jdistlib/code/ci/master/tree/'
                    }

                    licenses {
                        license {
                            name 'GNU General Public License version 2.0 (GPLv2)'
                            url 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html'
                        }
                    }

                    developers {
                        developer {
                            id 'robbyjo'
                            name 'Robby Joehanes'
                            email 'robyjoehanes@hsl.harvard.edu'
                        }
                        developer {
                            id 'danking'
                            name 'Daniel King'
                            email 'dking@broadinstitute.org'
                        }
                    }
                }
            }
        }
    }
}

artifactory {
    publish {
        contextUrl = 'http://oss.jfrog.org'
        repository {
            repoKey = 'oss-snapshot-local'
            username = project.properties.bintrayUserName
            password = project.properties.bintrayApiKey
        }
    }
}

artifactoryPublish {
    onlyIf { version.endsWith("SNAPSHOT") }
}

install {
    repositories.mavenInstaller {
        pom.artifactId = archivesBaseName
    }
}
