rootProject.name = 'JDistlib'
include 'jdistlib-cuda', 'jdistlib-opencl', 'jdistlib-vulkan', 'jdistlib-all'
project(':jdistlib-cuda').projectDir = file('accelerators/cuda')
project(':jdistlib-opencl').projectDir = file('accelerators/opencl')
project(':jdistlib-vulkan').projectDir = file('accelerators/vulkan')
project(':jdistlib-all').projectDir = file('distribution/all')
