/*
 * Copyright (C) 2026 Roby Joehanes
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */
package jdistlib.math;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

/** References generated by src/test/R/generate-r461-integrate.R. */
public class R461IntegrateAuditTest {
	private static void check(IntegrationResult result, double value, double error,
			int subdivisions, int status, double valueTolerance, double errorTolerance) {
		String details = "value=" + result.result + ", error=" + result.abserr
				+ ", subdivisions=" + result.last + ", evaluations=" + result.neval
				+ ", status=" + result.ier;
		assertEquals(result.message(), status, result.ier);
		assertEquals(details, value, result.result, valueTolerance);
		assertEquals(details, error, result.abserr, errorTolerance);
		assertEquals(details, subdivisions, result.last);
	}

	@Test
	public void finiteDqagsMatchesR461ReferenceCorpus() {
		check(Integrate.integrate(x -> x * x, 0, 1, 1e-12, 1e-12, 100),
				1.0 / 3.0, 3.70074341541719e-15, 1, 0, 2e-16, 2e-28);
		check(Integrate.integrate(x -> 1.0 / Math.sqrt(x), 0, 1,
				1e-10, 1e-10, 200),
				2.0, 5.77315972805081e-15, 6, 0, 1e-15, 1e-15);
		check(Integrate.integrate(x -> 1.0 / Math.sqrt(Math.abs(x - 0.3)), 0, 1,
				1e-9, 1e-9, 300),
				2.76876516807849, 4.9293902293357e-14, 10, 0, 3e-13, 2e-25);
		check(Integrate.integrate(x -> x < 0.12345 ? -2.0 : 3.0, -1, 2,
				1e-11, 1e-11, 200),
				3.38274999999948, 9.53398463164426e-12, 37, 0, 8e-13, 1e-15);
		check(Integrate.integrate(x -> Math.sin(1000.0 * x), 0, 1,
				1e-10, 1e-10, 500),
				0.00043762092370916, 5.94446812217435e-11, 126, 0,
				3e-15, 5e-16);
	}

	@Test
	public void infiniteDqagiMatchesR461ReferenceCorpus() {
		check(Integrate.integrate(x -> Math.exp(-x), 0,
				Double.POSITIVE_INFINITY, 1e-10, 1e-10, 200),
				1.0, 5.842606742906e-11, 5, 0, 2e-15, 2e-23);
		check(Integrate.integrate(x -> 1.0 / (1.0 + x * x),
				Double.NEGATIVE_INFINITY, Double.POSITIVE_INFINITY,
				1e-10, 1e-10, 200),
				Math.PI, 2.5779652693418e-10, 3, 0, 4e-15, 2e-22);
		check(Integrate.integrate(x -> 1.0 / Math.sqrt(x), 0,
				Double.POSITIVE_INFINITY, 1e-8, 1e-8, 200),
				-8.55304198454141e-11, 1.656772781800145e-10, 22, 5,
				3e-20, 3e-20);
	}

	@Test
	public void statusesAndBoundaryInputsAreReported() {
		check(Integrate.integrate(x -> 1.0 / Math.sqrt(x), 0, 1,
				1e-14, 1e-14, 1),
				1.96752571487957, 0.952686763515677, 1, 1, 5e-15, 3e-15);
		check(Integrate.integrate(Math::exp, 0, 1,
				1e-14, 1e-14, 1000),
				1.7182818284590453, 1.9076760487502457e-14, 1, 2,
				3e-15, 3e-28);
		check(Integrate.integrate(Math::sin, 0, Double.POSITIVE_INFINITY,
				1e-8, 1e-8, 200),
				23283401.958539866, 51572570.149891488, 172, 4,
				2e-5, 2e-5);

		IntegrationResult zeroWidth = Integrate.integrate(x -> x, 2, 2,
				1e-12, 1e-12, 100);
		assertTrue(zeroWidth.isSuccess());
		assertEquals(0.0, zeroWidth.result, 0.0);
		assertEquals(1, zeroWidth.last);
		assertEquals(21, zeroWidth.neval);

		assertEquals(6, Integrate.integrate(null, 0, 1).ier);
		assertEquals(6, Integrate.integrate(x -> x, Double.NaN, 1).ier);
		assertEquals(6, Integrate.integrate(x -> x, 0, 1,
				Double.NaN, 1e-8, 100).ier);
		assertEquals(6, Integrate.integrate(x -> x, 0, 1,
				0.0, 1e-20, 100).ier);
		assertEquals(6, Integrate.integrate(x -> x, 0, 1,
				1e-8, 1e-8, 0).ier);
		assertEquals(3, Integrate.integrate(x -> Double.NaN, 0, 1).ier);
	}
}
