package jdistlib;

import static org.junit.Assert.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.junit.Test;
import jdistlib.accelerator.*;
import jdistlib.inference.*;
import jdistlib.inference.solver.*;

/** Fixed deterministic references generated by benchmarks/audit2/inference. */
public class InferenceAudit2Test {
	private static final Map<String, Double> REFERENCES = references();
	private static Map<String, Double> references() {
		Map<String, Double> values = new HashMap<String, Double>();
		try (BufferedReader reader = new BufferedReader(new InputStreamReader(
				InferenceAudit2Test.class.getResourceAsStream("/jdistlib/inference/audit2-reference.csv"), StandardCharsets.UTF_8))) {
			reader.readLine(); String line;
			while ((line = reader.readLine()) != null) {
				String[] cells = line.replace("\"", "").split(",");
				values.put(cells[0] + "/" + cells[1] + "/" + cells[2], Double.valueOf(cells[3]));
			}
		} catch (IOException exception) { throw new ExceptionInInitializerError(exception); }
		return values;
	}
	private static void reference(String key, double actual, double tolerance) {
		double expected = REFERENCES.get(key);
		assertEquals(key, expected, actual, tolerance * Math.max(1, Math.abs(expected)));
	}
	private static ChainResult[] chains(String kind, int n) {
		ChainResult[] result = new ChainResult[4];
		for (int c = 0; c < 4; c++) {
			double[][] draws = new double[n][1]; IterationStats[] stats = new IterationStats[n]; double previous = 0;
			for (int i = 0; i < n; i++) {
				double v = Math.sin((i + 1) * (c + 2) * 1.17) + Math.cos((i + 1) * .31 + c);
				previous = i == 0 ? v : .7 * previous + v;
				draws[i][0] = "antithetic".equals(kind) ? (i % 2 == 0 ? previous : -previous)
						: "skewed".equals(kind) ? Math.exp(previous * .4)
						: "tied".equals(kind) ? Math.rint(previous) : previous;
				stats[i] = new IterationStats(true, 1, 1, Double.NaN, 0, false, 0, 0);
			}
			result[c] = new ChainResult(draws, new double[n], stats, null, null, ChainResult.Status.SUCCESS, Collections.<String>emptyList());
		}
		return result;
	}
	@Test public void modernDiagnosticsMatchPosteriorForFiveChainGeometries() {
		for (String kind : new String[] {"ordinary", "antithetic", "skewed", "tied", "odd"}) {
			ParameterDiagnostics p = McmcDiagnostics.analyze(chains(kind, "odd".equals(kind) ? 257 : 256)).parameter("state[0]");
			reference("diagnostics/" + kind + "/rhat", p.rHat(), 3e-12);
			reference("diagnostics/" + kind + "/ess_bulk", p.bulkEffectiveSampleSize(), 3e-11);
			reference("diagnostics/" + kind + "/ess_tail", p.tailEffectiveSampleSize(), 3e-11);
			reference("diagnostics/" + kind + "/mcse_mean", p.monteCarloStandardError(), 3e-12);
		}
	}
	@Test public void stuckChainsCannotReportReliableDiagnostics() {
		ChainResult[] base = chains("ordinary", 64);
		for (int c = 0; c < base.length; c++) base[c] = new ChainResult(new double[64][1], new double[64], base[c].statistics(), null, null, ChainResult.Status.SUCCESS, Collections.<String>emptyList());
		ParameterDiagnostics p = McmcDiagnostics.analyze(base).parameter("state[0]");
		assertTrue(Double.isNaN(p.rHat())); assertTrue(Double.isNaN(p.bulkEffectiveSampleSize())); assertFalse(p.reliable());
	}
	@Test public void generalizedParetoFitMatchesLooIncludingNegativeShape() {
		for (String kind : new String[] {"smooth", "heavy", "bounded"}) {
			double[] ratios = new double[200];
			for (int i = 0; i < ratios.length; i++) {
				double p = ((i * 73) % 200 + .5) / 200;
				ratios[i] = "smooth".equals(kind) ? .8 * Math.sin((i + 1) * .7) + .4 * Math.cos((i + 1) * 1.3)
						: ("heavy".equals(kind) ? -1.2 : .3) * Math.log1p(-p);
			}
			ParetoSmoothedImportanceSampling.Result fit = ParetoSmoothedImportanceSampling.smooth(ratios);
			reference("psis/" + kind + "/k", fit.paretoK(), 2e-11);
			for (int i : new int[] {0, 31, 199}) reference("psis/" + kind + "/weight" + i, fit.logWeights()[i], 2e-11);
		}
	}
	@Test public void predictiveCriteriaMatchLoo() {
		double[][] likelihood = new double[200][3];
		for (int i = 0; i < 200; i++) {
			likelihood[i][0] = -2 + .3 * Math.sin((i + 1) * .4);
			likelihood[i][1] = -1 + .2 * Math.cos((i + 1) * .6);
			likelihood[i][2] = -3 + .5 * Math.sin((i + 1) * .2);
		}
		PointwiseLogLikelihoodDraws draws = new PointwiseLogLikelihoodDraws(ObservationMetadata.ungrouped("a", "b", "c"), likelihood, new int[] {0, 200});
		Waic.Result waic = Waic.compute(draws);
		reference("predictive/matrix/loo", PsisLoo.compute(draws).elpd(), 2e-11);
		reference("predictive/matrix/waic", waic.elpd(), 2e-12);
		reference("predictive/matrix/pwaic", waic.effectiveNumberOfParameters(), 2e-12);
		reference("predictive/matrix/waic_se", waic.standardError(), 2e-12);
	}
	@Test public void eigenAndSvdAreInvariantToExtremeGlobalScaling() {
		CpuComputeBackend cpu = new CpuComputeBackend();
		for (double scale : new double[] {1, 1e-200, 1e200}) {
			double[] eigen = cpu.dsyev(new double[] {2 * scale, scale, scale, 2 * scale}, 2).eigenvalues();
			assertEquals(1, eigen[0] / scale, 2e-14); assertEquals(3, eigen[1] / scale, 2e-14);
			SingularValueDecomposition svd = cpu.dgesvd(new double[] {scale, 2*scale, 3*scale, 4*scale, 5*scale, 6*scale}, 3, 2);
			for (int i = 0; i < 2; i++) reference("matrix/svd/s" + (i+1), svd.singularValues()[i] / scale, 2e-13);
			double[] u = svd.leftSingularVectors(), vt = svd.rightSingularVectorsTransposed();
			for (int r = 0; r < 3; r++) for (int c = 0; c < 2; c++) {
				double reconstructed = 0;
				for (int k = 0; k < 2; k++) reconstructed += u[r*2+k] * (svd.singularValues()[k] / scale) * vt[k*2+c];
				assertEquals(r*2+c+1, reconstructed, 2e-13);
			}
		}
		for (float scale : new float[] {1e-25f, 1e25f}) {
			float[] eigen = cpu.ssyev(new float[] {2*scale,scale,scale,2*scale},2).eigenvalues();
			assertEquals(1, eigen[0]/scale, 2e-6); assertEquals(3,eigen[1]/scale,2e-6);
			float[] singular = cpu.sgesvd(new float[] {scale,2*scale,3*scale,4*scale,5*scale,6*scale},3,2).singularValues();
			for (int i=0;i<2;i++) reference("matrix/svd/s"+(i+1),singular[i]/scale,2e-6);
		}
		double[] solved = cpu.dgetrf(new double[] {4,1,1,3},2).solve(new double[] {1,2});
		for (int i=0;i<2;i++) reference("matrix/solve/x"+(i+1),solved[i],2e-14);
		double[] sparse = cpu.dcsrpotrf(jdistlib.matrix.CsrMatrix.fromDense(2,2,new double[]{4,1,1,3},0),MatrixTriangle.LOWER).solve(new double[]{1,2});
		for (int i=0;i<2;i++) reference("matrix/sparse_solve/x"+(i+1),sparse[i],2e-14);
	}
	@Test public void zeroBlasCoefficientsDoNotReadDisabledOperands() {
		CpuComputeBackend cpu = new CpuComputeBackend();
		double[] output = {Double.NaN, Double.POSITIVE_INFINITY};
		cpu.dgemv(MatrixTranspose.NONE,2,2,1,new double[]{1,2,3,4},new double[]{1,2},0,output);
		assertArrayEquals(new double[]{5,11},output,0);
		cpu.dgemv(MatrixTranspose.NONE,2,2,0,new double[]{Double.NaN,2,3,4},new double[]{1,2},2,output);
		assertArrayEquals(new double[]{10,22},output,0);
		float[] single = {Float.NaN};
		cpu.sgemm(MatrixTranspose.NONE,MatrixTranspose.NONE,1,1,1,1,new float[]{2},new float[]{3},0,single);
		assertEquals(6,single[0],0);
	}
	@Test public void odeMatchesDeSolveAndAnalyticRotation() {
		double[] times = {.1,1,3};
		double[][] actual = OdeSolver.integrate((t,y,p,d,f)->{f[0]=y[1];f[1]=-y[0];},new double[]{1,0},0,times,null,null,new OdeSolver.Options(1e-10,1e-12,.01,100000));
		for(int i=0;i<times.length;i++) {
			String time = i == 0 ? "0.1" : i == 1 ? "1" : "3";
			for(int j=0;j<2;j++) reference("ode/"+time+"/y"+(j+1),actual[i][j],2e-10);
			assertEquals(Math.cos(times[i]),actual[i][0],2e-10);assertEquals(-Math.sin(times[i]),actual[i][1],2e-10);
		}
	}
	@Test public void tinyOdeIntervalsAreValidWhenTimeCanAdvance() {
		double[] times = {1e-20,2e-20};
		double[][] actual=OdeSolver.integrate((t,y,p,d,f)->f[0]=1,new double[]{0},0,times,null,null,OdeSolver.Options.defaults());
		assertEquals(1e-20,actual[0][0],1e-34);assertEquals(2e-20,actual[1][0],1e-34);
		double[][] stiff = StiffOdeSolver.integrate((t,y,p,d,f)->f[0]=1e20,new double[]{0},0,times,null,null,StiffOdeSolver.Options.defaults());
		assertEquals(1,stiff[0][0],1e-9);assertEquals(2,stiff[1][0],1e-9);
	}
	@Test public void algebraicRootsDoNotDependOnResidualUnits() {
		for(double scale:new double[]{1,1e-20,1e20}) {
			double[] root=AlgebraicSolver.solve((x,p,d,f)->f[0]=scale*(x[0]-2),new double[]{0},null,null,new AlgebraicSolver.Options(scale*1e-10,1e-6,50)).solution();
			assertEquals(2,root[0],2e-10);
		}
	}
	@Test public void finiteDifferenceGradientMatchesNumDerivAndAnalyticDerivative() {
		double[] x={.7,-1.2,.3}, gradient=new double[3];
		Gradients.finiteDifference(v->-.5*(v[0]*v[0]+v[1]*v[1]+v[2]*v[2])+Math.sin(v[0]*v[1])+Math.log1p(Math.exp(v[2])))
				.logDensityAndGradient(x,gradient);
		double[] exact={-x[0]+x[1]*Math.cos(x[0]*x[1]),-x[1]+x[0]*Math.cos(x[0]*x[1]),-x[2]+1/(1+Math.exp(-x[2]))};
		for(int i=0;i<3;i++){reference("gradient/smooth/g"+(i+1),gradient[i],1e-9);assertEquals(exact[i],gradient[i],1e-9);}
	}
}
