package jdistlib;

import static java.lang.Math.abs;
import static java.lang.Math.max;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import jdistlib.math.Bessel;
import jdistlib.math.MathFunctions;
import jdistlib.math.PolyGamma;
import jdistlib.rng.MersenneTwister;
import jdistlib.rng.RandomEngine;

/** Regression values generated by src/test/R/generate-r461-nmath.R with R 4.6.1. */
public class R461NmathAuditTest {

	private static void close(double expected, double actual, double relativeTolerance) {
		if (Double.isNaN(expected)) {
			assertTrue("actual=" + actual, Double.isNaN(actual));
			return;
		}
		if (Double.isInfinite(expected)) {
			assertEquals(expected, actual, 0.);
			return;
		}
		double tolerance = relativeTolerance * max(abs(expected), 1e-300);
		assertEquals("expected=" + expected + ", actual=" + actual,
			expected, actual, tolerance);
	}

	@Test
	public void betaFamilyMatchesR461() {
		close(-1.5920265589610949, Beta.density(.4, .25, 3.5, true), 3e-14);
		close(-746.09868869236743, Beta.cumulative(.9833, 43779, .06728, true, true), 2e-12);
		close(3.0517578124999993e-05,
			Beta.quantile(-248.06320004817743, 25, 6, true, true), 5e-14);
		assertEquals(1., Beta.cumulative(-1, 0, 2, true, false), 0.);
		assertEquals(1., Beta.cumulative(.4, 0, 2, true, false), 0.);
		assertEquals(0., Beta.cumulative(.4, 2, 0, true, false), 0.);
		close(-.10606283088456528, NonCentralBeta.density(.3, 2.5, 7, 11, true), 2e-13);
	}

	@Test
	public void gammaAndChiSquareFamiliesMatchR461() {
		assertEquals(Double.NEGATIVE_INFINITY,
			Gamma.density(Double.MIN_VALUE, .5, 2, true), 0.);
		close(-.097128825327760612, Gamma.cumulative(1e-8, .125, 3, false, true), 2e-14);
		assertEquals(0., Gamma.quantile(-700, .125, 3, true, true), 0.);
		close(-14.373794322256366, ChiSquare.density(41, 7.5, true), 3e-14);
		close(-13.544359061872939, ChiSquare.cumulative(41, 7.5, false, true), 3e-14);
		close(2.2314424168402068e-75,
			ChiSquare.quantile(-650, 7.5, true, true), 3e-13);
		close(-16.023767809162738, NonCentralChiSquare.density(17, 4.5, 80, true), 2e-13);
		close(-15.609252558841815,
			NonCentralChiSquare.cumulative(17, 4.5, 80, true, true), 2e-12);
		close(-19.154665749614185,
			NonCentralChiSquare.cumulative(220, 4.5, 80, false, true), 2e-9);
		close(122.76546465007237,
			NonCentralChiSquare.quantile(.975, 4.5, 80, true, false), 2e-9);
	}

	@Test
	public void hypergeometricAndWilcoxonMatchR461() {
		close(-2.9966321810519871, HyperGeometric.density(23, 150, 230, 70, true), 3e-14);
		close(-4.0633107288157255,
			HyperGeometric.cumulative(35, 150, 230, 70, false, true), 3e-13);
		assertEquals(39., HyperGeometric.quantile(.999, 150, 230, 70, true, false), 0.);

		Wilcoxon wilcoxon = new Wilcoxon(20, 30);
		close(-10.231448016174586, wilcoxon.density(137, true), 3e-14);
		close(-.00047539583868997477, wilcoxon.cumulative(137, false, true), 3e-13);
		assertEquals(399., wilcoxon.quantile(.975, true, false), 0.);
		/* The Loeffler cache is one-dimensional; this size was impractical with
		 * the historical three-dimensional recursive cache. */
		assertFalse(Double.isNaN(new Wilcoxon(60, 80).density(1200, true)));

		SignRank signRank = new SignRank(12);
		close(-4.5111036769490234, signRank.density(20, true), 3e-14);
		close(-.078700834950075613, signRank.cumulative(20, false, true), 3e-14);
		assertEquals(64., signRank.quantile(.975, true, false), 0.);
		assertEquals(0., signRank.cumulative(-.5, true, false), 0.);
	}

	@Test
	public void besselAndPolygammaMatchR461() {
		close(.22389077914123565, Bessel.j(2, 2e-16), 3e-14);
		close(-.061100713793116268, Bessel.j(12.25, 7.75), 5e-14);
		close(.25060012879322796, Bessel.y(12.25, 7.75), 5e-14);
		close(.010284129181934708, Bessel.i(1500, 2.25, true), 5e-14);
		close(.047533822460251667, Bessel.k(700, 2.25, true), 5e-14);
		close(45171.497249121632, PolyGamma.psigamma(-.375, 5), 2e-13);
		close(-109.61275521521785, PolyGamma.psigamma(3.25, 12), 2e-13);
	}

	@Test
	public void discreteFamiliesMatchR461() {
		close(-9.913487552536127, Binomial.density(2, 1e16, 1e-18, true), 3e-14);
		close(-.01038983833763806,
			Binomial.cumulative(3, 1e9, 1e-8, false, true), 3e-13);
		assertEquals(0., Binomial.quantile(-700, 1e9, 1e-8, true, true), 0.);
		close(-4.9999999315497981e183,
			Poisson.density(1e200, 1e200 + 1e192, true), 3e-14);
		close(-23.370343308504282, Poisson.cumulative(170, 100, false, true), 3e-13);
		assertEquals(0., Poisson.quantile(-700, 100, true, true), 0.);
		close(-9982.0512934843227,
			NegBinomial.density(2, 1e16, .999999999999, true), 3e-14);
		close(-9982.2724664366106,
			NegBinomial.density_mu(2, 1e16, 10000, true), 3e-14);
		close(-1087.010920610966,
			NegBinomial.cumulative_mu(15000, 1e16, 10000, false, true), 2e-11);
		assertEquals(6510., NegBinomial.quantile_mu(-700, 1e16, 10000, true, true), 0.);
	}

	@Test
	public void continuousFamiliesAndArithmeticHelpersMatchR461() {
		assertEquals(Double.NEGATIVE_INFINITY, Cauchy.density(1e200, -3, 2.5, true), 0.);
		close(-460.74545775278438, Cauchy.cumulative(1e200, -3, 2.5, false, true), 3e-14);
		close(2100., Exponential.quantile(-700, 3, false, true), 3e-15);
		close(-2170.1188526168808, F.density(1e100, 3.5, 17, true), 3e-14);
		close(3.4825010165124035e36, F.quantile(-700, 3.5, 17, false, true), 3e-12);
		assertTrue(Double.isNaN(LogNormal.density(Double.POSITIVE_INFINITY,
			Double.POSITIVE_INFINITY, 0, false)));
		close(-332.66666666666669,
			Logistic.cumulative(1000, 2, 3, false, true), 3e-15);
		close(-7.0263275343571283e242, T.quantile(-700, 1.25, true, true), 3e-13);
		close(12430.656024396403, Weibull.quantile(-700, .75, 2, false, true), 3e-14);
		close(-3.1219840143358368,
			NonCentralF.cumulative(8, 4.5, 11, 7, false, true), 3e-12);
		close(-3.7979583123021783,
			NonCentralT.cumulative(9, 7.5, 4, false, true), 3e-11);
		close(-7.1584072330687629,
			Tukey.cumulative(8, 3, 7, 20, false, true), 2e-7);

		assertEquals(2., MathFunctions.round(2.5, 0), 0.);
		assertEquals(4., MathFunctions.round(3.5, 0), 0.);
		assertEquals(0., MathFunctions.round(Double.MIN_VALUE, 323), 0.);
		close(1.2345678901234559e-300,
			MathFunctions.round(1.234567890123456e-300, 315), 2e-15);
		close(-12345.700000000001, MathFunctions.signif(-12345.6789, 6), 3e-15);
		close(1.1000000000000004e308, MathFunctions.signif(1.09e308, 2), 3e-15);
		assertEquals(1., MathFunctions.sinpi(.5), 0.);
		assertEquals(-1., MathFunctions.sinpi(-.5), 0.);
		assertEquals(-1., MathFunctions.tanpi(-.25), 0.);
	}

	@Test
	public void rngBoundariesAndLargeHypergeometricParametersArePreserved() {
		RandomEngine random = new MersenneTwister(461);
		assertEquals(.5, Beta.random(Double.POSITIVE_INFINITY,
			Double.POSITIVE_INFINITY, random), 0.);
		assertEquals(0., Beta.random(0, 2, random), 0.);
		assertEquals(1., Beta.random(2, 0, random), 0.);
		assertTrue(Double.isNaN(NonCentralChiSquare.random(2, Double.NaN, random)));
		assertEquals(Double.POSITIVE_INFINITY,
			NonCentralChiSquare.random(Double.POSITIVE_INFINITY, 0, random), 0.);

		double n1 = 3_000_000_000., n2 = 1_000_000_000., sample = 2.;
		double draw = HyperGeometric.random(n1, n2, sample, new FixedRandom(.25));
		assertEquals(HyperGeometric.quantile(.25, n1, n2, sample, false, false), draw, 0.);
	}

	private static final class FixedRandom extends RandomEngine {
		private static final long serialVersionUID = 1L;
		private final double value;
		FixedRandom(double value) { this.value = value; }
		@Override public double nextGaussian() { return 0.; }
		@Override public double nextDouble() { return value; }
		@Override public float nextFloat() { return (float) value; }
		@Override public int nextInt() { return 0; }
		@Override public int nextInt(int n) { return 0; }
		@Override public long nextLong() { return 0; }
		@Override public long nextLong(long n) { return 0; }
		@Override public RandomEngine clone() { return new FixedRandom(value); }
	}
}
