/* Copyright (C) 2026 Roby Joehanes; GPL-2.0-or-later */
package jdistlib.inference.lang;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/** Ahead-of-time Java source generation for a validated embedded model script. */
public final class ModelSourceGenerator {
	private ModelSourceGenerator() {}

	public static String generate(String fullyQualifiedClassName, String script) {
		if (fullyQualifiedClassName == null || script == null
				|| !fullyQualifiedClassName.matches("[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*"))
			throw new IllegalArgumentException("valid class name and script are required");
		int split = fullyQualifiedClassName.lastIndexOf('.');
		String packageName = split < 0 ? null : fullyQualifiedClassName.substring(0, split);
		String simpleName = split < 0 ? fullyQualifiedClassName
				: fullyQualifiedClassName.substring(split + 1);
		StringBuilder source = new StringBuilder();
		if (packageName != null) source.append("package ").append(packageName).append(";\n\n");
		source.append("import java.util.Map;\n")
				.append("import jdistlib.inference.lang.CompiledModelScript;\n")
				.append("import jdistlib.inference.lang.GeneratedModelFactory;\n")
				.append("import jdistlib.inference.lang.ModelScript;\n\n")
				.append("/** Generated by JDistlib ModelSourceGenerator; do not edit. */\n")
				.append("public final class ").append(simpleName)
				.append(" implements GeneratedModelFactory {\n")
				.append("  private static final String SOURCE = \"").append(javaString(script)).append("\";\n")
				.append("  @Override public CompiledModelScript compile(Map<String, double[]> data) {\n")
				.append("    return ModelScript.compile(SOURCE, data);\n  }\n")
				.append("  @Override public String sourceHash() { return \"")
				.append(hash(script)).append("\"; }\n}\n");
		return source.toString();
	}

	public static String hash(String script) {
		try {
			byte[] digest = MessageDigest.getInstance("SHA-256")
					.digest(script.getBytes(StandardCharsets.UTF_8));
			StringBuilder result = new StringBuilder();
			for (byte value : digest) result.append(String.format("%02x", value & 0xff));
			return result.toString();
		} catch (NoSuchAlgorithmException exception) {
			throw new IllegalStateException("SHA-256 is unavailable", exception);
		}
	}

	private static String javaString(String value) {
		StringBuilder result = new StringBuilder();
		for (int i = 0; i < value.length(); i++) {
			char c = value.charAt(i);
			if (c == '\\') result.append("\\\\");
			else if (c == '"') result.append("\\\"");
			else if (c == '\n') result.append("\\n");
			else if (c == '\r') result.append("\\r");
			else if (c == '\t') result.append("\\t");
			else if (c < 32 || c > 126) result.append(String.format("\\u%04x", (int) c));
			else result.append(c);
		}
		return result.toString();
	}
}
