/* Copyright (C) 2026 Roby Joehanes; GPL-2.0-or-later */
package jdistlib.accelerator;

import jdistlib.matrix.FloatCsrMatrix;

/** Deterministic CPU reference algorithms for FP32 backend methods. */
final class CpuSinglePrecisionLinearAlgebra {
	private CpuSinglePrecisionLinearAlgebra() {}
	static void saxpy(int count, float alpha, float[] x, int xo, int xs, float[] y, int yo, int ys) {
		checkRegion(count,x,xo,xs);checkRegion(count,y,yo,ys);for(int i=0,xi=xo,yi=yo;i<count;i++,xi+=xs,yi+=ys)y[yi]=alpha*x[xi]+y[yi];
	}
	static float sdot(int count,float[]x,int xo,int xs,float[]y,int yo,int ys){checkRegion(count,x,xo,xs);checkRegion(count,y,yo,ys);float result=0;
		for(int i=0,xi=xo,yi=yo;i<count;i++,xi+=xs,yi+=ys)result+=x[xi]*y[yi];return result;}
	static float snrm2(int count,float[]x,int offset,int stride){checkRegion(count,x,offset,stride);float scale=0,sum=1;
		for(int i=0,index=offset;i<count;i++,index+=stride){float value=Math.abs(x[index]);if(value!=0){if(scale<value){float ratio=scale/value;sum=1+sum*ratio*ratio;scale=value;}else{float ratio=value/scale;sum+=ratio*ratio;}}}
		return scale==0?0:scale*(float)Math.sqrt(sum);}
	static void sgemv(MatrixTranspose transpose,int rows,int columns,float alpha,float[]matrix,float[]x,float beta,float[]y){checkMatrix(rows,columns,matrix);requireTranspose(transpose);
		int input=transpose==MatrixTranspose.NONE?columns:rows,output=transpose==MatrixTranspose.NONE?rows:columns;
		if(x==null||x.length!=input||y==null||y.length!=output)throw new IllegalArgumentException("SGEMV vector dimensions do not conform");
		for(int row=0;row<output;row++){float sum=0;for(int column=0;column<input;column++)sum+=(transpose==MatrixTranspose.NONE?matrix[row*columns+column]:matrix[column*columns+row])*x[column];y[row]=alpha*sum+beta*y[row];}}
	static void sgemm(MatrixTranspose ta,MatrixTranspose tb,int rows,int columns,int shared,float alpha,float[]left,float[]right,float beta,float[]result){requireTranspose(ta);requireTranspose(tb);
		checkMatrix(ta==MatrixTranspose.NONE?rows:shared,ta==MatrixTranspose.NONE?shared:rows,left);checkMatrix(tb==MatrixTranspose.NONE?shared:columns,tb==MatrixTranspose.NONE?columns:shared,right);
		if(result==null||result.length!=rows*columns)throw new IllegalArgumentException("SGEMM result dimensions do not conform");
		for(int row=0;row<rows;row++)for(int column=0;column<columns;column++){float sum=0;for(int inner=0;inner<shared;inner++){float a=ta==MatrixTranspose.NONE?left[row*shared+inner]:left[inner*rows+row];float b=tb==MatrixTranspose.NONE?right[inner*columns+column]:right[column*shared+inner];sum+=a*b;}int index=row*columns+column;result[index]=alpha*sum+beta*result[index];}}
	static void scsrmv(float alpha,FloatCsrMatrix matrix,float[]x,float beta,float[]y){if(matrix==null||x==null||x.length!=matrix.columns()||y==null||y.length!=matrix.rows())throw new IllegalArgumentException("FP32 CSR matrix-vector dimensions do not conform");
		float[]values=matrix.values();int[]columns=matrix.columnIndices(),starts=matrix.rowStarts();for(int row=0;row<matrix.rows();row++){float sum=0;for(int z=starts[row]-1;z<starts[row+1]-1;z++)sum+=values[z]*x[columns[z]-1];y[row]=alpha*sum+beta*y[row];}}
	static void scsrmm(float alpha,FloatCsrMatrix matrix,float[]right,int rightColumns,float beta,float[]result){if(matrix==null||rightColumns<1||right==null||right.length!=matrix.columns()*rightColumns||result==null||result.length!=matrix.rows()*rightColumns)throw new IllegalArgumentException("FP32 CSR matrix-matrix dimensions do not conform");
		float[]values=matrix.values();int[]columns=matrix.columnIndices(),starts=matrix.rowStarts();for(int row=0;row<matrix.rows();row++)for(int column=0;column<rightColumns;column++){float sum=0;for(int z=starts[row]-1;z<starts[row+1]-1;z++)sum+=values[z]*right[(columns[z]-1)*rightColumns+column];int index=row*rightColumns+column;result[index]=alpha*sum+beta*result[index];}}
	static FloatCholeskyFactor spotrf(float[]matrix,int dimension){checkMatrix(dimension,dimension,matrix);checkFinite(matrix);float[]lower=new float[matrix.length];
		for(int row=0;row<dimension;row++)for(int column=0;column<=row;column++){float sum=matrix[row*dimension+column];for(int k=0;k<column;k++)sum-=lower[row*dimension+k]*lower[column*dimension+k];if(row==column){if(!(sum>0)||!Float.isFinite(sum))throw new IllegalArgumentException("matrix is not finite symmetric positive definite at minor "+(row+1));lower[row*dimension+column]=(float)Math.sqrt(sum);}else lower[row*dimension+column]=sum/lower[column*dimension+column];}return new FloatCholeskyFactor(dimension,lower);}
	static FloatPivotedQrFactor sgeqp3(float[]matrix,int rows,int columns){checkMatrix(rows,columns,matrix);checkFinite(matrix);float[]qr=matrix.clone();int reflectors=Math.min(rows,columns);float[]tau=new float[reflectors];int[]pivot=new int[columns];for(int i=0;i<columns;i++)pivot[i]=i;
		for(int k=0;k<reflectors;k++){int selected=k;float selectedNorm=-1;for(int column=k;column<columns;column++){float norm=0;for(int row=k;row<rows;row++){float value=qr[row*columns+column];norm+=value*value;}if(norm>selectedNorm){selectedNorm=norm;selected=column;}}if(selected!=k){for(int row=0;row<rows;row++){int first=row*columns+k,second=row*columns+selected;float value=qr[first];qr[first]=qr[second];qr[second]=value;}int value=pivot[k];pivot[k]=pivot[selected];pivot[selected]=value;}
			float norm=snrm2(rows-k,qr,k*columns+k,columns);if(norm==0){tau[k]=0;continue;}float alpha=qr[k*columns+k],diagonal=-Math.copySign(norm,alpha);tau[k]=(diagonal-alpha)/diagonal;float denominator=alpha-diagonal;qr[k*columns+k]=diagonal;for(int row=k+1;row<rows;row++)qr[row*columns+k]/=denominator;for(int column=k+1;column<columns;column++){float product=qr[k*columns+column];for(int row=k+1;row<rows;row++)product+=qr[row*columns+k]*qr[row*columns+column];product*=tau[k];qr[k*columns+column]-=product;for(int row=k+1;row<rows;row++)qr[row*columns+column]-=qr[row*columns+k]*product;}}
		return new FloatPivotedQrFactor(rows,columns,qr,tau,pivot);}
	static FloatSymmetricEigenDecomposition ssyev(float[]matrix,int dimension){checkMatrix(dimension,dimension,matrix);checkFinite(matrix);checkSymmetric(matrix,dimension);float[]a=matrix.clone(),vectors=identity(dimension);float epsilon=16*Math.ulp(1.0f);int maximum=Math.max(32,8*dimension);
		for(int sweep=0;sweep<maximum;sweep++){boolean changed=false;for(int p=0;p<dimension-1;p++)for(int q=p+1;q<dimension;q++){float apq=a[p*dimension+q],threshold=epsilon*(Math.abs(a[p*dimension+p])+Math.abs(a[q*dimension+q])+1);if(Math.abs(apq)<=threshold)continue;changed=true;float app=a[p*dimension+p],aqq=a[q*dimension+q],tau=(aqq-app)/(2*apq);float t=Math.copySign(1.0f/(Math.abs(tau)+(float)Math.hypot(1,tau)),tau),c=1.0f/(float)Math.hypot(1,t),s=t*c;
			for(int k=0;k<dimension;k++)if(k!=p&&k!=q){float akp=a[k*dimension+p],akq=a[k*dimension+q],nextP=c*akp-s*akq,nextQ=s*akp+c*akq;a[k*dimension+p]=a[p*dimension+k]=nextP;a[k*dimension+q]=a[q*dimension+k]=nextQ;}a[p*dimension+p]=c*c*app-2*s*c*apq+s*s*aqq;a[q*dimension+q]=s*s*app+2*s*c*apq+c*c*aqq;a[p*dimension+q]=a[q*dimension+p]=0;
			for(int row=0;row<dimension;row++){float vp=vectors[row*dimension+p],vq=vectors[row*dimension+q];vectors[row*dimension+p]=c*vp-s*vq;vectors[row*dimension+q]=s*vp+c*vq;}}
			if(!changed)break;if(sweep+1==maximum)throw new IllegalStateException("FP32 symmetric eigendecomposition did not converge");}
		float[]eigenvalues=new float[dimension];for(int i=0;i<dimension;i++)eigenvalues[i]=a[i*dimension+i];sortEigenpairs(eigenvalues,vectors,dimension);canonicalizeColumns(vectors,dimension,dimension);return new FloatSymmetricEigenDecomposition(dimension,eigenvalues,vectors);}
	static FloatSingularValueDecomposition sgesvd(float[]matrix,int rows,int columns){checkMatrix(rows,columns,matrix);checkFinite(matrix);if(rows>=columns)return tallSvd(matrix,rows,columns);float[]transposed=new float[matrix.length];for(int row=0;row<rows;row++)for(int column=0;column<columns;column++)transposed[column*rows+row]=matrix[row*columns+column];FloatSingularValueDecomposition reverse=tallSvd(transposed,columns,rows);float[]reverseU=reverse.leftSingularVectors(),reverseVt=reverse.rightSingularVectorsTransposed(),left=new float[rows*rows],rightTransposed=new float[rows*columns];for(int row=0;row<rows;row++)for(int column=0;column<rows;column++)left[row*rows+column]=reverseVt[column*rows+row];for(int component=0;component<rows;component++)for(int column=0;column<columns;column++)rightTransposed[component*columns+column]=reverseU[column*rows+component];return new FloatSingularValueDecomposition(rows,columns,reverse.singularValues(),left,rightTransposed);}
	private static FloatSingularValueDecomposition tallSvd(float[]matrix,int rows,int columns){float[]work=matrix.clone(),vectors=identity(columns);float epsilon=16*Math.ulp(1.0f);int maximum=Math.max(48,12*columns);for(int sweep=0;sweep<maximum;sweep++){boolean changed=false;for(int p=0;p<columns-1;p++)for(int q=p+1;q<columns;q++){float alpha=0,beta=0,gamma=0;for(int row=0;row<rows;row++){float left=work[row*columns+p],right=work[row*columns+q];alpha+=left*left;beta+=right*right;gamma+=left*right;}if(gamma==0||Math.abs(gamma)<=epsilon*(float)Math.sqrt(alpha*beta))continue;changed=true;float zeta=(beta-alpha)/(2*gamma),t=Math.copySign(1.0f/(Math.abs(zeta)+(float)Math.hypot(1,zeta)),zeta),c=1.0f/(float)Math.hypot(1,t),s=c*t;for(int row=0;row<rows;row++){int pi=row*columns+p,qi=row*columns+q;float left=work[pi],right=work[qi];work[pi]=c*left-s*right;work[qi]=s*left+c*right;}for(int row=0;row<columns;row++){int pi=row*columns+p,qi=row*columns+q;float left=vectors[pi],right=vectors[qi];vectors[pi]=c*left-s*right;vectors[qi]=s*left+c*right;}}if(!changed)break;if(sweep+1==maximum)throw new IllegalStateException("FP32 SVD did not converge");}
		float[]singular=new float[columns];for(int column=0;column<columns;column++)singular[column]=columnNorm(work,rows,columns,column);for(int i=0;i<columns-1;i++){int selected=i;for(int j=i+1;j<columns;j++)if(singular[j]>singular[selected])selected=j;if(selected!=i){float value=singular[i];singular[i]=singular[selected];singular[selected]=value;swapColumns(work,rows,columns,i,selected);swapColumns(vectors,columns,columns,i,selected);}}
		float[]left=new float[rows*columns];float threshold=Math.max(rows,columns)*Math.ulp(1.0f)*singular[0];for(int column=0;column<columns;column++){if(singular[column]>threshold)for(int row=0;row<rows;row++)left[row*columns+column]=work[row*columns+column]/singular[column];else completeOrthonormalColumn(left,rows,columns,column);}canonicalizePairedColumns(left,vectors,rows,columns);float[]rightTransposed=new float[columns*columns];for(int row=0;row<columns;row++)for(int column=0;column<columns;column++)rightTransposed[row*columns+column]=vectors[column*columns+row];return new FloatSingularValueDecomposition(rows,columns,singular,left,rightTransposed);}
	private static float[] identity(int dimension){float[]result=new float[dimension*dimension];for(int i=0;i<dimension;i++)result[i*dimension+i]=1;return result;}
	private static float columnNorm(float[]matrix,int rows,int columns,int column){float scale=0,sum=1;for(int row=0;row<rows;row++){float value=Math.abs(matrix[row*columns+column]);if(value!=0){if(scale<value){float ratio=scale/value;sum=1+sum*ratio*ratio;scale=value;}else{float ratio=value/scale;sum+=ratio*ratio;}}}return scale==0?0:scale*(float)Math.sqrt(sum);}
	private static void swapColumns(float[]matrix,int rows,int columns,int first,int second){for(int row=0;row<rows;row++){int a=row*columns+first,b=row*columns+second;float value=matrix[a];matrix[a]=matrix[b];matrix[b]=value;}}
	private static void completeOrthonormalColumn(float[]matrix,int rows,int columns,int column){for(int candidate=0;candidate<rows;candidate++){for(int row=0;row<rows;row++)matrix[row*columns+column]=row==candidate?1:0;for(int previous=0;previous<column;previous++){float product=0;for(int row=0;row<rows;row++)product+=matrix[row*columns+previous]*matrix[row*columns+column];for(int row=0;row<rows;row++)matrix[row*columns+column]-=product*matrix[row*columns+previous];}float norm=columnNorm(matrix,rows,columns,column);if(norm>16*Math.ulp(1.0f)){for(int row=0;row<rows;row++)matrix[row*columns+column]/=norm;return;}}throw new IllegalStateException("cannot complete FP32 singular-vector basis");}
	private static void sortEigenpairs(float[]values,float[]vectors,int dimension){for(int i=0;i<dimension-1;i++){int selected=i;for(int j=i+1;j<dimension;j++)if(values[j]<values[selected])selected=j;if(selected!=i){float value=values[i];values[i]=values[selected];values[selected]=value;swapColumns(vectors,dimension,dimension,i,selected);}}}
	private static void canonicalizeColumns(float[]matrix,int rows,int columns){for(int column=0;column<columns;column++){int largest=0;for(int row=1;row<rows;row++)if(Math.abs(matrix[row*columns+column])>Math.abs(matrix[largest*columns+column]))largest=row;if(matrix[largest*columns+column]<0)for(int row=0;row<rows;row++)matrix[row*columns+column]=-matrix[row*columns+column];}}
	private static void canonicalizePairedColumns(float[]left,float[]right,int rows,int columns){for(int column=0;column<columns;column++){int largest=0;for(int row=1;row<rows;row++)if(Math.abs(left[row*columns+column])>Math.abs(left[largest*columns+column]))largest=row;if(left[largest*columns+column]<0){for(int row=0;row<rows;row++)left[row*columns+column]=-left[row*columns+column];for(int row=0;row<columns;row++)right[row*columns+column]=-right[row*columns+column];}}}
	private static void checkSymmetric(float[]matrix,int dimension){float scale=1;for(float value:matrix)scale=Math.max(scale,Math.abs(value));float tolerance=64*Math.ulp(1.0f)*scale;for(int row=0;row<dimension;row++)for(int column=row+1;column<dimension;column++)if(Math.abs(matrix[row*dimension+column]-matrix[column*dimension+row])>tolerance)throw new IllegalArgumentException("FP32 eigenvalue matrix must be symmetric");}
	private static void checkRegion(int count,float[]values,int offset,int stride){if(count<0||values==null||offset<0||stride<1||(count>0&&(long)offset+(long)(count-1)*stride>=values.length))throw new IllegalArgumentException("invalid FP32 strided vector region");}
	private static void checkMatrix(int rows,int columns,float[]matrix){if(rows<1||columns<1||matrix==null||matrix.length!=rows*columns)throw new IllegalArgumentException("invalid FP32 row-major matrix dimensions");}
	private static void requireTranspose(MatrixTranspose transpose){if(transpose==null)throw new IllegalArgumentException("matrix transpose policy is required");}
	private static void checkFinite(float[]values){for(float value:values)if(!Float.isFinite(value))throw new IllegalArgumentException("factorization matrix must be finite");}
}
